"""
PowerSense AI — Intelligent Electricity Management Assistant
--------------------------------------------------------------
A Streamlit dashboard implementing:
  1. Home dashboard with KPI cards
  2. Sidebar navigation across all feature areas
  3. Bill Analyzer (upload -> real PDF text extraction -> analysis)
  4. Consumption analytics (trend chart, peak usage, cost)
  5. Multi-agent architecture visualization
  6. AI Assistant chat, RAG-grounded
  7. Confidence / evidence blocks (computed, not hardcoded)
  8. RAG "Knowledge Center" — real TF-IDF retrieval, PDFs can be added live
  9. Savings Simulator
  10. Anomaly / problem detection with severity levels

WHAT'S REAL VS. STILL SIMULATED (read this before a demo)
--------------------------------------------------------
REAL now:
  - RAG: the Knowledge Center articles are chunked and indexed with TF-IDF
    (scikit-learn). The AI Assistant, "why is my bill high", and Problem
    Detection's "possible causes" all retrieve actual top-matching chunks
    via cosine similarity from the SAME index — not separate fixed lists
    that could silently disagree with each other. Upload your own PDFs
    from the Knowledge Center page and test retrieval live.
  - Bill upload: PDFs are read with pypdf and parsed with regex for
    consumer ID / units / total / readings / due date. Found fields are
    used as-is; anything not found falls back to demo data, and the UI
    says explicitly which happened.
  - Confidence score: a z-score of this month's units against historical
    mean/std, not a hardcoded number.
  - Agent Status (sidebar + dashboard): reflects whether each capability
    actually works in this environment (e.g. RAG turns red if
    scikit-learn isn't installed) instead of a constant green.
  - Tariff rate: editable in Settings and actually flows through every
    calculation in the app — it's no longer a display-only input next to
    a hardcoded constant.
  - Recommendations: savings scale with the household's own current usage
    (% of their real units) instead of being an identical fixed list for
    every user.
  - Dashboard "Analyze Bill" / "Ask AI" buttons and the "Issues Detected"
    KPI: wired to real navigation and to the same health/anomaly
    functions the dedicated pages use, instead of doing nothing / showing
    a fixed "2".
  - Hourly usage curve: generated from the household's own monthly units
    via a simple day-shape model, and "Peak Usage Window" is computed
    from that curve — not two independent hardcoded values that could
    contradict each other.
  - Optional live LLM: if you set an Anthropic API key in Settings (or the
    ANTHROPIC_API_KEY env var), chat answers are generated by a real model
    call using retrieved chunks + bill data as context. Without a key,
    answers are assembled directly from the retrieved text instead.

STILL SIMULATED / SIMPLIFIED (be upfront about these — they're labeled in
the UI wherever they appear, not hidden):
  - No OCR — scanned/image bills aren't parsed, only text-based PDFs.
  - The 12-month consumption history is a synthetic series (fixed random
    seed) with no persistent per-user store; it resets every session.
    This is now labeled "Simulated data" directly on the Consumption page
    rather than presented as if it were real meter history.
  - The hourly load curve is a modeled shape scaled to real monthly
    units, not measured interval data — labeled as such in its heading.
  - The tariff model is a single flat Rs./unit rate, not a real
    multi-slab schedule with domestic/commercial categories.
  - Removed outright rather than faked: the Settings page no longer has
    Language/Currency selectors or alert toggles that didn't do anything —
    only the one control that actually affects the app (tariff rate)
    remains.
  - Each "agent" is still a Python function, not an autonomous tool-using
    agent with its own reasoning loop — the Agent Status caption says so.

Run with:
    pip install -r requirements.txt
    streamlit run app.py
"""

import io
import os
import random
import re
from datetime import datetime, timedelta

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
import streamlit as st

# Optional dependencies — the app degrades gracefully (with a visible
# warning) instead of crashing if any of these aren't installed.
try:
    from pypdf import PdfReader
    PYPDF_AVAILABLE = True
except ImportError:
    PYPDF_AVAILABLE = False

try:
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.metrics.pairwise import cosine_similarity
    SKLEARN_AVAILABLE = True
except ImportError:
    SKLEARN_AVAILABLE = False

try:
    import anthropic
    ANTHROPIC_AVAILABLE = True
except ImportError:
    ANTHROPIC_AVAILABLE = False

# ----------------------------------------------------------------------
# PAGE CONFIG & GLOBAL STYLE
# ----------------------------------------------------------------------

st.set_page_config(
    page_title="PowerSense AI",
    page_icon="⚡",
    layout="wide",
    initial_sidebar_state="expanded",
)

CUSTOM_CSS = """
<style>
    #MainMenu {visibility: hidden;}
    footer {visibility: hidden;}

    .ps-header {
        padding: 0.25rem 0 1rem 0;
        border-bottom: 1px solid rgba(120,120,120,0.2);
        margin-bottom: 1.5rem;
    }
    .ps-title { font-size: 1.9rem; font-weight: 700; margin-bottom: 0; }
    .ps-subtitle { color: #8a8f98; font-size: 0.95rem; margin-top: -6px; }

    .kpi-card {
        background: linear-gradient(135deg, rgba(99,102,241,0.08), rgba(16,185,129,0.06));
        border: 1px solid rgba(120,120,120,0.15);
        border-radius: 14px;
        padding: 1rem 1.1rem;
        height: 100%;
    }
    .kpi-label { font-size: 0.8rem; color: #8a8f98; margin-bottom: 4px; }
    .kpi-value { font-size: 1.5rem; font-weight: 700; }
    .kpi-delta-up { color: #ef4444; font-size: 0.82rem; }
    .kpi-delta-down { color: #10b981; font-size: 0.82rem; }

    .badge {
        display: inline-block;
        padding: 2px 10px;
        border-radius: 999px;
        font-size: 0.78rem;
        font-weight: 600;
    }
    .badge-green  { background: rgba(16,185,129,0.15); color: #10b981; }
    .badge-yellow { background: rgba(234,179,8,0.15);  color: #ca8a04; }
    .badge-orange { background: rgba(249,115,22,0.15); color: #ea580c; }
    .badge-red    { background: rgba(239,68,68,0.15);  color: #ef4444; }

    .agent-box {
        border: 1px solid rgba(120,120,120,0.2);
        border-radius: 12px;
        padding: 0.7rem 0.9rem;
        text-align: center;
        font-size: 0.85rem;
        font-weight: 600;
    }
    .evidence-box {
        background: rgba(120,120,120,0.06);
        border-left: 3px solid #6366f1;
        border-radius: 8px;
        padding: 0.7rem 0.9rem;
        font-size: 0.88rem;
    }
    .source-chip {
        display: inline-block;
        background: rgba(99,102,241,0.1);
        color: #6366f1;
        padding: 3px 10px;
        border-radius: 999px;
        font-size: 0.78rem;
        margin: 2px 4px 2px 0;
    }
    .mode-chip-llm {
        display: inline-block;
        background: rgba(16,185,129,0.12);
        color: #10b981;
        padding: 2px 9px;
        border-radius: 999px;
        font-size: 0.74rem;
        margin-bottom: 6px;
    }
    .mode-chip-retrieval {
        display: inline-block;
        background: rgba(234,179,8,0.12);
        color: #ca8a04;
        padding: 2px 9px;
        border-radius: 999px;
        font-size: 0.74rem;
        margin-bottom: 6px;
    }
</style>
"""
st.markdown(CUSTOM_CSS, unsafe_allow_html=True)

# ----------------------------------------------------------------------
# MOCK CONSUMPTION DATA (still synthetic — see note at top of file)
# ----------------------------------------------------------------------



if "consumption_df" not in st.session_state:
    st.session_state.consumption_df = pd.DataFrame(columns=["month", "units"])

if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

if "bill_data" not in st.session_state:
    st.session_state.bill_data = None

if "custom_kb_chunks" not in st.session_state:
    st.session_state.custom_kb_chunks = []

if "uploaded_kb_files" not in st.session_state:
    st.session_state.uploaded_kb_files = []

if "anthropic_api_key" not in st.session_state:
    st.session_state.anthropic_api_key = ""

if "llm_model" not in st.session_state:
    st.session_state.llm_model = "claude-sonnet-5"

if "rate_per_unit" not in st.session_state:
    st.session_state.rate_per_unit = 42.0  # Rs. per kWh, editable in Settings — real, not decorative

if "nav_page" not in st.session_state:
    st.session_state.nav_page = "🏠 Dashboard"

df = st.session_state.consumption_df
RATE_PER_UNIT = st.session_state.rate_per_unit
if len(df) >= 2:
    current_units = int(df["units"].iloc[-1])
    previous_units = int(df["units"].iloc[-2])
    pct_change = round((current_units - previous_units) / previous_units * 100, 1) if previous_units else 0.0
    current_bill = int(current_units * RATE_PER_UNIT * 1.08)
    estimated_saving = int(current_units * 0.10 * RATE_PER_UNIT)
else:
    current_units = previous_units = 0
    pct_change = 0.0
    current_bill = estimated_saving = 0


# ----------------------------------------------------------------------
# KNOWLEDGE BASE — real article text (this is what actually gets
# chunked + indexed below, not just a list of titles)
# ----------------------------------------------------------------------

KNOWLEDGE_BASE = [
    {
        "title": "Electricity Tariff Slabs Explained",
        "category": "Tariffs",
        "content": (
            "Most residential electricity tariffs are structured in slabs, meaning the "
            "price per unit (kWh) increases as your total monthly consumption crosses "
            "certain thresholds, rather than every unit being billed at a single flat "
            "rate. A household using 150 units might pay a low rate on the first block "
            "and a higher rate only on the units above that block. This is why doubling "
            "your usage from one month to the next often more than doubles your bill — "
